rails-todo/config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos

end

rails-todo/app/models/todo.rb
class Todo < ActiveRecord::Base
end

rails-todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails-todo/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :content)
    end
end

rails-todo/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-todo/app/helpers/todos_helper.rb
module TodosHelper
end

rails-todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      Todo Demo App
    </title>
    <%= stylesheet_link_tag    'bootstrap/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'bootstrap/bootstrap-responsive.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row-fluid">
          <div class="span12 main-content">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

rails-todo/app/views/todo/index.html.erb
<div class="titlebar">
    <h1>Listing TODOs</h1>
    <%= form_tag("/post", method: "get", class: "form-group add-todo") do %>
      <%= text_field(:todo, :Title, class: "form-control todo-input") %>
      <%= text_field(:todo, :Content, class: "form-control todo-input") %>
      <button class="btn btn-primary" id="add-todo">
        <i class="icon-ok icon-white"></i>
      </button>
    <% end %>
</div>

<% @todos.each do |todo| %>
  <div class="todo">
    <div class="title">
      <%= todo.Title %>
    </div>
    <div class="content">
      <%= todo.Content %>
    </div>
  </div>
<% end %>

rails-todo/app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails-todo/app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

rails-todo/app/views/todos/index.html.erb
<h3 class="main-title">Listing TODOs</h3>
<%= button_to "+", new_todo_path, :class => "btn btn-success", :form_class => "add-todo", :method => :get %>
<div id="todos">
  <% @todos.each do|todo| %>
  <div class="row-fluid" id="todo">
    <div class="span3"><%= todo.title %></div>
    <div class="span5"><%= todo.content %></div>
    <div class="span4 actions">
      <%= button_to "Remove", todo, :class => "btn btn-danger", :method => :delete, data: { confirm: 'Are you sure?' } %>
      <%= button_to "Edit", edit_todo_path(todo), :class => "btn btn-info", :method => :get %>
    </div>
  </div>
  <% end %>
</div>

rails-todo/app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

rails-todo/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>